version: '3.8'

services:

  backend-production:
    image: backend-production
    build:
      context: bloglist-backend
      dockerfile: Dockerfile
    volumes:
      - ./bloglist-backend:/usr/src/app
      - node_modules:/usr/src/app/node_modules

  frontend-production:
    image: frontend-production
    build:
      context: bloglist-frontend 
      dockerfile: Dockerfile 
    volumes:
      - ./bloglist-frontend:/usr/src/app
    depends_on:
      - backend-production

  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy
    depends_on:
      - frontend-production

volumes:
  node_modules: